name: test-build

on:
  push:
  pull_request:
  pull_request_target:
    types: [labeled]

jobs:
  build:
    name: Test Secret Access
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'sure-test-it')

    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET_THINGY }}

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          if [ -z "$SUPER_SECRET" ]
          then
             echo "Secret not found"
             exit 1
          else
             echo "Secret found!"
             exit 0
          fi
