name: test-build

on:
  push:
  pull_request:

jobs:
  build:
    env:
      SUPER_SECRET: ${{ secrets.SUPER_SECRET_THINGY }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo "Hello $SUPER_SECRET"
